### ISSUE TITLE
Manipulating current collection 

### ISSUE THREAD

**Issue by NanoSector** [danielgsims/php-collections#46]
What methods are there to manipulate an existing collection? Every method now returns a new collection which is not what the methods describe or what one would expect of them.

**Comment by danielgsims** [comment]
The collection is immutable. You get a new collection back with whatever changes applied.

**Comment by NanoSector** [comment]
Yeah, I understood that much ;) I just think it's not a great design decision.

Either way I've since built my own version of collections, so you're free to dismiss this issue if you'd like.
