### ISSUE TITLE
Cookbook / Examples

### ISSUE THREAD

**Issue by danielgsims** [danielgsims/php-collections#49]
Start a cookbook or examples section for how to use this library! Show examples like sorting, filtering, pagination, etc!

**Comment by kodisto** [comment]
I'll take this on.

**Comment by raxhvl** [comment]
Do you have a reference in mind?

Are you looking at something like [This?](https://laravel.com/docs/5.5/collections#method-average)

**Comment by danielgsims** [comment]
The example from Laravel looks pretty good!

**Comment by danielgsims** [comment]
I created a page where we can add docs to, for anyone who might be looking at this. It is docs/Collection.md
